---
name: build
jobs:
  build:
    container:
      image: golang:latest
      env:
        REPO_NAME: github.com/degica/barcelona-cli
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: script
      run: |-
        make
'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
