---
name: build
jobs:
  build:
    container:
      image: golang:latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: script
      run: |
        git config --global --add safe.directory $PWD
        make
'on':
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
