---
name: test
jobs:
  test:
    container:
      image: golang:latest
      env:
        REPO_NAME: github.com/degica/barcelona-cli
        GLIDE_VERSION: 0.13.3
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: script
      run: |-
        make check
'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
